### PR TITLE
All bedrock export processes should support non-ASCII characters #159

### PR DESCRIPTION
**Pull request by payion**

### CODE REVIEW

**Comment by wimgielis** [comment]
Hello. Short question. Why do we do SetOutputCharacterSet in the Data tab rather than Prolog tab ?

**Comment by lotsaram** [comment]
> Hello. Short question. Why do we do SetOutputCharacterSet in the Data tab rather than Prolog tab ?

This is becasue of how TI treats text output files. They are separate entities per tab (e.g. if you re-use the output filename between prolog and data then any output generated on prolog will be overwritten as the fie is regenerated on data). Therefore the SetOutputCharacterSet needs to be addressed on the tab where the file is written.

**Comment by lotsaram** [comment]
Awesome. Thanks @payion !
Did you find you needed to add SetImportCharacterSet in the import processes or it just worked as is?

**Comment by wimgielis** [comment]
Thanks Lotsa. I did a test with TextOutput - I never needed that one and I always used AsciiOutput. All my code was on the Prolog tab so that’s why it worked.

**Pull request merged**
