### PR TITLE
}bedrock.cube.data.import. pQuote validation contradicts with pQuote processing for the empty and ASCII code case. Proposal is to remove pQuote validation.

### PR DESCRIPTION
**Pull request by 4rtem**

### CODE REVIEW

**Comment by lotsaram** [comment]
@4rtem still waiting on the requested changes. I am keen to get this imporvement in but I would like to see the extra validation to allow for numeric code definition of quote character.

**Comment by 4rtem** [comment]
@lotsaram , forgot about this, I will find time this week to close it.

**Comment by ahavas** [comment]
@lotsaram and @4rtem I am not going to pretend to know how Github works, but isn't Github row 445-466 what you're suggesting @lotsaram?

**Comment by lotsaram** [comment]
> @lotsaram and @4rtem I am not going to pretend to know how Github works, but isn't Github row 445-466 what you're suggesting @lotsaram?

Hi @ahavas yes it is. The issue with it is that it has been implemented to accept only exactly 3 numeric characters so for example semi-colon would only accept '059' and not '59'. Ideally it should accept either, and this processing logic for defining ascii characters should apply to both pQuote and pDelimiter. If we are going to fix the issue of accepting empty quote character then ideally I would like to clean up this other issue and do it all in one commit.

**Comment by lotsaram** [comment]
@4rtem just added new pull which affects this file so please rebase your fork if working on the pQuote issue. Also please look at #146 as better to do all birds with one stone.

**Comment by lotsaram** [comment]
closing and using #162

**Pull request closed without merging**
